[versions]
ksp = "2.3.4"
kotlin = "2.3.10"
kotlinxImmutableCollection = "0.4.0"

#compose
compose-bom = "2026.02.00"
activity-compose = "1.12.4"

#core
androidDesugarJdkLibs = "2.1.5"
androidx-core = "1.17.0"

androidx-lifecycle = "2.10.0"
androidx-room = "2.8.4"

timber = "5.0.1"
samanzamani = "1.7.1"
datetime = "0.9.0"
swipe = "1.3.0"
accompanist_pager = "0.36.0"
accompanist_pager_indicators = "0.36.0"
accompanist_permissions = "0.37.3"
accompanist_system_ui = "0.36.0"
lottie_compose = "6.7.1"
junit = "4.13.2"
junit-test = "3.5.1"
androidx-ext-junit = "1.3.0"
espresso_core = "3.7.0"
agp = "8.13.2"
google-services = "4.4.4"
material3Android = "1.4.0"
compose-test = "1.10.4"
androidxCoreSplashscreen = "1.2.0"
vico = "2.4.3"
androidxTracing = "1.3.0"
spotless = "8.2.1"
datastore = "1.2.0"

androidTools = "32.0.1"
androidxJunit = "1.2.1"

#firebase
firebasePerfPlugin = "2.0.2"
firebaseCrashlyticsPlugin = "3.0.6"
firebaseBom = "33.12.0"

constraintlayout = "2.2.1"
constraintlayout-compose = "1.1.1"

jetbrainsKotlinJvm = "2.3.10"

#koin
koin-bom = "4.1.1"

#decompose
decompose = "3.4.0"
decompose-essenty = "2.5.0"

#kotlinx-serialization
kotlinx-serialization = "1.10.0"

[libraries]
#core
androidx-core = { group = "androidx.core", name = "core-ktx", version.ref = "androidx-core" }
android-desugarJdkLibs = { group = "com.android.tools", name = "desugar_jdk_libs", version.ref = "androidDesugarJdkLibs" }

#kotlin
kotlinx-collections-immutable = { group = "org.jetbrains.kotlinx", name = "kotlinx-collections-immutable", version.ref = "kotlinxImmutableCollection" }
androidx-tracing-ktx = { group = "androidx.tracing", name = "tracing-ktx", version.ref = "androidxTracing" }

#compose
androidx-compose-activity = { group = "androidx.activity", name = "activity-compose", version.ref = "activity-compose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
androidx-material3-android = { group = "androidx.compose.material3", name = "material3-android", version.ref = "material3Android" }
constraintlayout-compose = { module = "androidx.constraintlayout:constraintlayout-compose", version.ref = "constraintlayout-compose" }

ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
lifecycle-runtime-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
lottie-compose = { group = "com.airbnb.android", name = "lottie-compose", version.ref = "lottie_compose" }

#data store
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore" }
androidx-datastore-preferences-core = { module = "androidx.datastore:datastore-preferences-core", version.ref = "datastore" }

#decompose
decompose = { module = "com.arkivanov.decompose:decompose", version.ref = "decompose" }
decompose-jetbrains = { module = "com.arkivanov.decompose:extensions-compose", version.ref = "decompose" }
decompose-experimental = { module = "com.arkivanov.decompose:extensions-compose-experimental", version.ref = "decompose" }
decompose-lifecycle-coroutines = { module = "com.arkivanov.essenty:lifecycle-coroutines", version.ref = "decompose-essenty" }

#room
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "androidx-room" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "androidx-room" }
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "androidx-room" }

#koin
koin-bom = { module = "io.insert-koin:koin-bom", version.ref = "koin-bom" }
koin-core = { module = "io.insert-koin:koin-core" }
koin-android = { module = "io.insert-koin:koin-android" }
koin-android-compose = { module = "io.insert-koin:koin-androidx-compose" }

#timber
timber = { group = "com.jakewharton.timber", name = "timber", version.ref = "timber" }

#lifecycle
androidx-lifecycle-livedata = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtime = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycle" }

#firebase
firebaseBom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebaseBom" }
firebaseMessaging = { group = "com.google.firebase", name = "firebase-messaging-ktx" }
firebaseAnalytics = { group = "com.google.firebase", name = "firebase-analytics-ktx" }
firebaseCrashlytics = { group = "com.google.firebase", name = "firebase-crashlytics-ktx" }

#samanzamani
samanzamani = { group = "com.github.samanzamani", name = "PersianDate", version.ref = "samanzamani" }

#datetime
datetime = { group = "io.github.vanpra.compose-material-dialogs", name = "datetime", version.ref = "datetime" }

#swipe
swipe = { group = "me.saket.swipe", name = "swipe", version.ref = "swipe" }

#accompanist
accompanist-pager = { group = "com.google.accompanist", name = "accompanist-pager", version.ref = "accompanist_pager" }
accompanist-pager-indicators = { group = "com.google.accompanist", name = "accompanist-pager-indicators", version.ref = "accompanist_pager_indicators" }
accompanist-permissions = { group = "com.google.accompanist", name = "accompanist-permissions", version.ref = "accompanist_permissions" }
accompanist-systemuicontroller = { group = "com.google.accompanist", name = "accompanist-systemuicontroller", version.ref = "accompanist_system_ui" }

#junit
junit = { group = "junit", name = "junit", version.ref = "junit" }

#test
androidx-test-ext = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-ext-junit" }
androidx-test-espresso = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso_core" }
androidx-compose-ui-test = { group = "androidx.compose.ui", name = "ui-test-junit4", version.ref = "compose-test" }

#splash
androidx-core-splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "androidxCoreSplashscreen" }

#kotlinx-serilization
kotlinx-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }

#vico
vico-compose = { group = "com.patrykandpatrick.vico", name = "compose", version.ref = "vico" }
vico-compose-m3 = { group = "com.patrykandpatrick.vico", name = "compose-m3", version.ref = "vico" }

# Dependencies of the included build-logic
android-gradlePlugin = { group = "com.android.tools.build", name = "gradle", version.ref = "agp" }
android-tools-common = { group = "com.android.tools", name = "common", version.ref = "androidTools" }
compose-gradlePlugin = { module = "org.jetbrains.kotlin:compose-compiler-gradle-plugin", version.ref = "kotlin" }
firebase-crashlytics-gradlePlugin = { group = "com.google.firebase", name = "firebase-crashlytics-gradle", version.ref = "firebaseCrashlyticsPlugin" }
firebase-performance-gradlePlugin = { group = "com.google.firebase", name = "perf-plugin", version.ref = "firebasePerfPlugin" }
kotlin-gradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
ksp-gradlePlugin = { group = "com.google.devtools.ksp", name = "com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }
room-gradlePlugin = { group = "androidx.room", name = "room-gradle-plugin", version.ref = "androidx-room" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }

[bundles]
compose = ["androidx-compose-activity", "androidx-material3-android", "lifecycle-runtime-compose",
    "lifecycle-viewmodel-compose", "lottie-compose", "constraintlayout-compose"]
room = ["room-runtime", "room-ktx"]
koin = ["koin-android-compose", "koin-core", "koin-android"]
firebase = ["firebaseMessaging", "firebaseAnalytics", "firebaseCrashlytics"]
accompanist = ["accompanist-pager", "accompanist-pager-indicators", "accompanist-permissions", "accompanist-systemuicontroller"]
test = ["androidx-test-ext", "androidx-test-espresso", "androidx-compose-ui-test"]
vico = ["vico-compose", "vico-compose-m3"]
decompose = ["decompose", "decompose-jetbrains", "decompose-experimental", "decompose-lifecycle-coroutines"]


[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
google-services = { id = "com.google.gms.google-services", version.ref = "google-services" }
com-android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "firebaseCrashlyticsPlugin" }
androidx-room = { id = "androidx.room", version.ref = "androidx-room" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }

# Plugins defined by this project
application = { id = "yadino.application", version = "unspecified" }
application-compose = { id = "application.compose", version = "unspecified" }
firebase = { id = "firebase", version = "unspecified" }
#yadino-android-application-flavors = { id = "yadino.android.application.flavors", version = "unspecified" }
presentation = { id = "presentation.module", version = "unspecified" }
di = { id = "di", version = "unspecified" }
library = { id = "library", version = "unspecified" }
library-compose = { id = "library.compose", version = "unspecified" }
db = { id = "db", version = "unspecified" }
decompose = { id = "decompose", version = "unspecified" }
jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "jetbrainsKotlinJvm" }